<?php
/**
 * @file
 */

/**
 * Implements hook_library_info().
 */
function fullcalendar_lib_library_info() {
  $path = backdrop_get_path('module', 'fullcalendar_lib') . '/libraries/fullcalendar';
  $libraries['fullcalendar'] = array(
    'title' => 'Fullcalendar recent',
    'website' => 'https://fullcalendar.io',
    'version' => '6.1.5',
    'js' => array(
      $path . '/dist/index.global.min.js' => array(),
      $path . '/packages/core/locales-all.global.min.js' => array(),
    ),
  );
  return $libraries;
}
