<?php
/**
 * @file
 */

/**
 * Implements hook_library_info().
 */
function fullcalendar_lib_library_info() {
  $path = backdrop_get_path('module', 'fullcalendar_lib') . '/libraries/fullcalendar/lib';
  $libraries['fullcalendar'] = array(
    'title' => 'Fullcalendar recent',
    'website' => 'https://fullcalendar.io',
    'version' => '5.10.2',
    'js' => array(
      $path . '/main.min.js' => array(),
      $path . '/locales-all.min.js' => array(),
    ),
    'css' => array($path . '/main.min.css' => array()),
  );
  return $libraries;
}
